name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.0.84
homepage: https://github.com/redleafsofts/betterplayer
documentation: https://github.com/redleafsofts/betterplayer/docs

environment:
  sdk: '>=3.2.0-0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  wakelock_plus: ^1.1.3
  meta: ^1.10.0
  flutter_widget_from_html_core: ^0.14.6
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.1
  collection: ^1.18.0
  xml: ^6.4.2

dev_dependencies:
  lint: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin